---
title: "Child Mortality: Global Causes of Death"
authors: Jonathan To- jto9331@uw.edu
         Hiba Abbas- hibaa3@uw.edu
         Kevin Baron- baronk2@uw.edu
date: "11/14/2022"
output: html_document
---

```{r setup, include=FALSE}
# knitr::opts_knit$set(root.dir = "C:/Users/Owner/Documents/kevin/school/university_of_washington/Informatics/2022-2023/Autumn_2022/Info_201/Projects/project-01/project-baronk2/docs")
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
source("../source/aggregated_table.R")
source("../source/chart_2.R")
source("../source/map-chart-3.R")
```


## Aggregated Table

```{r table, echo = FALSE}
aggregated_table
```



## Dynamic Paragraph





## Chart 1

Here is a bar chart.

```{r echo=FALSE, message=FALSE}


```



## Chart 2

Here is a pi chart showcasing the amount of deaths for each of the 13 causes in 2017.

```{r echo=FALSE, message=FALSE}
source("https://raw.github.com/info201b-au2022/project-baronk2/main//source/chart_2.R")

 ggplot(deaths_in_2017, aes(x="", y=deaths, fill=cause)) +
  geom_bar(stat="identity", width=1, color="black") +
  coord_polar("y", start=0) +
  
  theme_void()

```


## Chart 3

Here is a map showing where there have been the most child deaths globally from
2000 to 2017.


```{r map, echo=FALSE, message=FALSE}
get_deaths_map()
get_deaths_map_paragraph()
```
